[package]
name = "BCF"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
codespan-reporting = "0.11.1"
indoc = "2"
